logging:
    level:
        org:
            atmosphere: warn
server:
    port: ${PORT:8080}
spring:
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
    mustache:
        check-template-location: false
vaadin:
    launch-browser: true
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
